name: test-protomech

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-protomech:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.9

      # Test
      - name: Test
        run: |
          pixi run -e all pytest -v src/protomech
